tad function implementation
Fusion4Energy/F4Enix pull request #114
Opened 2024-11-25 09:41 UTC by AlbertoBittes

# Description
the functions get_tad and get_density were introduced for material object. Given a material composition and an input density, the function returns the TAD, and viceversa

## Type of change

Please select what type of change this is.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature 
    - [x] Non-breaking change which adds functionality
    - [ ] Breaking change fix or feature that would cause existing functionality to not work as expected

## Other changes

- [ ] This change requires a documentation update

# Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- test_get_tad
- test_get_density

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] General testing 
    - [ ] New and existing unit tests pass locally with my changes
    - [ ] Coverage is >80%

2024-11-26 06:06 UTC, Radiation-Transport commented
Thanks for this. Is this function taking into account the renormalization which mcnp does for tad of the material card with the material density of the cell card?

2024-11-26 07:50 UTC, dodu94 requested changes
All good, please merge the new developing into this to make the tests pass

2024-11-26 07:51 UTC, dodu94 commented
> Thanks for this. Is this function taking into account the renormalization which mcnp does for tad of the material card with the material density of the cell card?

Yes he's normalizing with the total fraction of the material

2024-11-28 09:22 UTC, dodu94 approved these changes

2024-11-28 09:22 UTC, merged