Jade compatibility
Fusion4Energy/F4Enix pull request #78
Opened 2024-06-12 14:19 UTC by AlbertoBittes

# Description

Please include a summary of the changes and the related issue (if applicable). Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

Additional dependencies introduced.
- Dependency 1
- Dependency 2

## Type of change

Please select what type of change this is.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature 
    - [ ] Non-breaking change which adds functionality
    - [ ] Breaking change fix or feature that would cause existing functionality to not work as expected

## Other changes

- [ ] This change requires a documentation update

# Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- Test A
- Test B
- etc

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] General testing 
    - [ ] New and existing unit tests pass locally with my changes
    - [ ] Coverage is >80%

2024-06-14 09:56 UTC, dodu94 requested changes
Thanks Alberto for this PR, as you will see I had a few comments but nothing big. The main problem that we have right now is execution time that skyrocketed and we need to understand why.

2024-06-14 09:56 UTC, dodu94 commented on src/f4enix/input/libmanager.py
* Update typing also in docstring (for instance of xsdir_path). I would also probably rename the argument itself since it can be much more than a path now.
* docstring of libmanager: restore the more complete definition of ``isotopes`` in the Attributes section
* use the asfile() method to open files that are in the resources. This is the only method that ensures to correctly use the file if the package was zipped
* ``check4zaid()`` return type is missing. Also restore return object docstring which was slightly more compete
* in ``check4zaid()`` we are performing the ``find_table()`` method a lot of times if we have many libraries in the case that the fake DF has been built starting from all the libraries available in an xsdir. I suggest to add an attribute in the init that is set to true if all the xsdir paths point to the same file so we can check it only once in those cases
* eliminate the ``warning`` package and only use ``logging.warn()``
* return type missing for ``get_libzaids()``
* the ``select_lib()`` function has nothing to do with F4Enix, it is specific to JADE. we should put it back there as a standalone function taking a libmanager as argument.

2024-06-14 09:56 UTC, dodu94 commented on src/f4enix/input/materials.py
* ``PAT_COMMENT``, ``PAT_MAT`` and ``PAT_MX`` are already imported from F4Enix constants, the new code redefines them and I believe it should not
* Not a big fan of mixing the OpenMC material stuff here since there is a good chance that this would be deprecated soon if the API is used. I would suggest to create an OpenMC material subclass instead to keep the additional code separate. It should be fairly simple

2024-06-14 09:56 UTC, dodu94 commented on src/f4enix/output/MCNPoutput.py
* docstring of ``assign_tally_description()`` is incomplete
* avoid print warning, use ``logging.warn()`` instead

2024-06-14 09:56 UTC, dodu94 commented on src/f4enix/output/meshtal.py
Can you explain why there is a need to set the fmehses as attributes here in ``FMESH1D``?

2024-06-14 09:56 UTC, dodu94 commented on tests/libmanager_test.py
* why the ``XSDIR_FILE`` that is used now is the default of the package and not the one given in the test files like before?
* ``select_lib()`` tests should be brought back to JADE

2024-06-25 10:31 UTC, AlbertoBittes commented on src/f4enix/output/meshtal.py
What I do is that I import the attributes from a "normal" FMESH class, that has been already instantiated.
What happens is that the codes starts reading the meshtal, reads the first rows of the FMESH and checks the dimension. If it is a 1D mesh, then the code instantiates the FMESH1D instead. However, to read the FMESH, one should reopen the file and re-read again the FMESH, which can be time consuming for big files. So, if the FMESH is 1D, one simply passes the attributes of the FMESH that have been already read and goes on with reading the bins and the values.

2024-06-25 10:37 UTC, dodu94 commented on src/f4enix/output/meshtal.py
ah ok, got it, thanks.

2024-06-25 13:20 UTC, dodu94 commented on src/f4enix/input/acepyne.py
yes move it back to JADE for the moment being, thanks.

2024-06-25 13:57 UTC, AlbertoBittes commented on src/f4enix/input/materials.py
I really think that once the OpenMC API will be used we can just delete the functions from this class

2024-06-25 14:03 UTC, dodu94 commented on src/f4enix/input/materials.py
That is why I would like to separate the openMC code. In this way, when everything is done with the OpenMC API, it will be easier to just delete this subclass and not touch the main one

2024-06-25 14:12 UTC, AlbertoBittes commented on src/f4enix/input/materials.py
This doesn't simplify, as it would imply adding further if-statements in various JADE and F4Enix routines to check the code that is used. This will have to be removed later and I should basically add complexity to the code and remove it later

2024-06-26 08:04 UTC, dodu94 approved these changes

2024-06-26 08:05 UTC, merged